export default {
    LOAD_USER_DATA : "LOAD_USER_DATA",
    DELETE_USER : "DELETE_USER",
    UPDATE_USER : "UPDATE_USER",
    CHANGE_EDIT : "CHANGE_EDIT" ,
    ADD_USER : "ADD_USER",
    CANCEL_EDIT : "CANCEL_EDIT",
    SEARCH_USER:"SEARCH_USER"
}